version: '3'
services:
  transactional:
    build: API_SIMIT_Transactional/
    ports:
      - "8000:8000"
  query:
    build: API_SIMIT_Query/
    ports:
      - "8001:8001"
  mail:
    build: API_SIMIT_Mail/
    ports:
      - "8002:8002"
  redis:
    image: "redis:alpine"